// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozsaydarjridkiywzjrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96c2F5ZGFyanJpZGtpeXd6anJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTc2NDUsImV4cCI6MjA2MjU3MzY0NX0.USZpIxHrFvENSNQsk3IIf1lsTEjI2ziuGB1eNVubr1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);